name: CI Code

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout code 👋
        uses: actions/checkout@v3
      - name: Install Go 🗳
        uses: actions/setup-go@v3
      - name: Run GoReleaser 🚀
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: build --rm-dist --snapshot --skip-post-hooks
          workdir: .
          main: ../../cmd/geo-api
      - name: Run Tests
        run: go test -v ./...
